### ISSUE TITLE
Return all the details in json

### ISSUE THREAD

**Issue by RCasatta** [RCasatta/EternityWallAndroid#10]
like view and others

**Comment by RCasatta** [comment]
Use an DiskLruCache to store detail of a message and show immediately content to the user it he has already loaded it once. Than in background ask anyway to the API (to get eventual new replies, likes, views and other stuff updated)

**Comment by RCasatta** [comment]
Updated API to return all the details of the rankings

**Comment by lvaccaro** [comment]
the reply message is the same of the current message, ex. 
http://eternitywall.it/m/723bb0c6c64e303d9be3262a9df31a54b5b26f8440ae022c694817e3c20854a3
http://eternitywall.it/m/723bb0c6c64e303d9be3262a9df31a54b5b26f8440ae022c694817e3c20854a3?format=json

**Comment by lvaccaro** [comment]
view and weekView have the same value

**Comment by RCasatta** [comment]
fixed bug of the same message, view and weekView are the same for message not older than a week
