### ISSUE TITLE
Adding combo in sending

### ISSUE THREAD

**Issue by RCasatta** [RCasatta/EternityWallAndroid#22]
To choose between anonymous sending (like it's working right now) and with account if there is one defined

**Comment by lvaccaro** [comment]
do you prefer use a default option? for example: default use the account, and a checkbox for anonymous message?

**Comment by RCasatta** [comment]
I already started to work on this using a spinner... Maybe multiple accounts one day...

**Comment by RCasatta** [comment]
remove checkbox "Send as anonymous" since we can change from spinner
